### ISSUE TITLE
Move orphan instances to a separate package

### ISSUE THREAD

**Issue by sol** [haskell-compat/base-compat#18]

**Comment by RyanGlScott** [comment]
If you create the `sol/base-orphans` repo, I'd be willing to port over the existing orphan instances in `base-compat`.

**Comment by sol** [comment]
Hey, sorry to be slow on this.  I'll do it tomorrow. Alternatively, if you want to have it under your account I'm fine with that too.

**Comment by RyanGlScott** [comment]
We do have quite a collection of compatibility packages now (`base-compat`, `base-orphans`, `setenv`, my `mtl-compat` package, etc.). Mind if I create a GitHub group (e.g., `haskell-compat`) and eventually move all of these repos there?

**Comment by sol** [comment]
Sounds good!

**Comment by RyanGlScott** [comment]
I did a quick port of the orphan instances in this repo to [`base-orphans`](https://github.com/haskell-compat/base-orphans). Can you review it when you get a chance? One thing I'm a bit indecisive about is the name of the exported module (I dubbed it `BaseOrphans` for now).

**Comment by sol** [comment]
Yes, I was puzzled about that, too.  I had `Data.Orphans` in mind.

**Comment by RyanGlScott** [comment]
I guess if we had to classify what orphans are under a top-level module name in `base`, `Data` probably makes the most sense. I'll change it as a part of a pull request I'm working on.

**Comment by sol** [comment]
@RyanGlScott I'll remove the orphans from `base-compat` now, or are you already on it?

**Comment by RyanGlScott** [comment]
I'm a bit busy at the moment, so go ahead.
