### ISSUE TITLE
Giant list of missing/changed functions

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/base-compat#24]
After scanning through the GHC and `base` changelogs, I made a list of functions that were introduced or changed in later versions of `base` that would be good candidates for `base-compat`. I intentionally skipped the `GHC.`-prefixed modules for now, since they tend to be rather volatile.
### ~~`base-4.3.0.0`:~~ (Edit: these are no longer needed due to dropping support for `base-4.2.0.0` and earlier)
- [x] ~~`mfilter` added to `Control.Monad`~~
- [x] ~~`partitionEithers` (in `Data.Either`) was made lazier~~
- [x] ~~`swap` added to `Data.Tuple`~~
- [x] ~~`castCUCharToChar`, `castCharToCUChar`, `castCSCharToChar`, and `castCharToCSChar` added to `Foreign.C.String`~~
- [x] ~~`unsafeLocalState` added to `Foreign.Marshal`~~
- [x] ~~`hGetBufSome` added to `System.IO`~~
### `base-4.4.0.0`:
- [ ] `gcd 0 0` now returns `0`
- [ ] `forkIOWithUnmask`, `forkOn`, and `forkOnWithUnmask`, added to `Control.Concurrent`
- [ ] `allowInterrupt` added to `Control.Exception`
- [x] `Control.Monad.ST.Unsafe` and `Control.Monad.ST.Lazy.Unsafe` modules added
- [ ] `inits`, `tails`, `intersperse`, and `intersectBy` (in `Data.List`) are lazier
- [x] `Foreign.ForeignPtr.Unsafe` and `Foreign.Marshal.Unsafe` modules added
- [x] `Data.String` reexports `String`, `lines`, `unlines`, and `unwords`
- [ ] `maybeNew` (in `Foreign.Marshal.Utils`) had its type generalized from `(a -> IO (Ptr a)) -> Maybe a -> IO (Ptr a)` to `(a -> IO (Ptr b)) -> Maybe a -> IO (Ptr b)`. (Make sure to check this with `typediff`.)
- [ ] `catchIOError` and `tryIOError` added to `System.IO.Error`
- [x] `unsafeDupablePerformIO` added to `System.IO.Unsafe`
- [ ] `peekFilePath`, `puts`, and `c_safe_open` added to `System.Posix.Internals`
  - [ ] On non-Windows platforms, `peekFilePathLen` added to `System.Posix.Internals`
### `base-4.5.0.0`:
- [ ] `fixIO` (in `System.IO`) is now thread-safe
- [x] `unsafeFixIO` added to `System.IO.Unsafe`
### `base-4.5.1.0`:
- [ ] `writeChan` (in `Control.Concurrent.Chan`) fixed to avoid potential race condition
- [ ] `hGetBufSome` (in `System.IO`) fixed to avoid blocking on Windows
### `base-4.6.0.0`:
- [x] `forkFinally` added to `Control.Concurrent`
- [ ] `mkWeakMVar`, `modifyMVarMasked`, and `modifyMVarMasked_` added to `Control.Concurrent.MVar`
- [x] `bitDefault`, `testBitDefault`, and `popCountDefault` added to `Data.Bits`
- [x] `modifyIORef'` and `atomicModifyIORef'` added to `Data.IORef`
- [x] `modifySTRef'` added to `Data.STRef`
- [ ] `getExecutablePath` added to `System.Environment` (requires `peekFilePath`, so this will need `System.Posix.Internals.Compat` to work)
### ~~`base-4.7.0.0`:~~
- [x] `byteSwap16`, `byteSwap32`, and `byteSwap64` added to `Data.Word`. Their implementations require functions in `ghc-prim` not available to earlier versions of GHC, but it should be possible to define equivalent implementations without using `ghc-prim`.
- [X] ~~`eNOTSUP` added to `Foreign.C.Error`~~ (Edit: This is isn't possible to backport without involving a `configure` script, which isn't desirable.)
- [x] `showFFloatAlt` and `showGFloatAlt` added to `Numeric`
### `base-4.7.0.2`:
- [ ] `inits` (in `Data.List`) had a performance bug fixed
- [ ] `trace` (in `Debug.Trace`) fixed to handle null bytes properly
### ~~`base-4.8.0.0`:~~
- [x] `toIntegralSized` added to `Data.Bits` (due to its use of `bitSizeMaybe` in its implementation, however, this can only be backported back to `base-4.7.0.0`)
- [x] `nub` and `nubBy`'s implementations (in `Data.List`) were changed such that the arguments to `==` and `eq`, respectively, are swapped
- [x] `fillBytes` added to `Foreign.Marshal.Utils`
### ~~`base-4.9.0.0`~~
- [x] `Data.Ratio.{denominator,numerator}` have no `Integral` constraint anymore
- [x] Generalize `Debug.Trace.{traceM, traceShowM}` from `Monad` to `Applicative`
- [x] Generalise `forever` from `Monad` to `Applicative`
- [x] Generalise `filterM`, `mapAndUnzipM`, `zipWithM`, `zipWithM_`, `replicateM`, and `replicateM_` from `Monad` to `Applicative`
- [x] `Data.Functor.Const` module added
- [x] `errorWithoutStackTrace` function added to `Prelude` (it's just the old behavior of `error`, I believe)
- [x] `forkOSWithUnmask` function added to `Control.Concurrent`
### ~~`base-4.10.0.0`~~
- [x] `fromLeft` and `fromRight` added to `Data.Either`
- [x] `gcoerceWith` added to `Data.Type.Coercion`
- [x] `plusForeignPtr` added to `Foreign.ForeignPtr`
- [x] `asProxyTypeOf`'s type has been generalized in `Data.Proxy`
- [x] `minimumBy`/`maximumBy` are now implemented with `foldl` instead of `foldr`
### ~~`base-4.11.0.0`~~
- [x] `Semigroup((<>))` added to the `Prelude`
- [x] `(<&>)` added to `Data.Functor`
- [x] `iterate'` added to `Data.List`
- [x] `showHFloat` to `Numeric`
- [x] `Type.Reflection.withTypeable` is now polymorphic in the `RuntimeRep` of its result
### ~~`base-4.12.0.0`~~
- [x] `Data.Functor.Contravariant` is now in `base`
- [x] `$!` and `throw` are levity polymorphic
### ~~`base-4.13.0.0`~~
- [x] `MonadFail(..)` added to the `Prelude` and `Control.Monad` (and `Monad.fail` removed)
### ~~`base-4.14.0.0`~~
- [x] `isResourceVanishedError`, `resourceVanishedErrorType`, and `isResourceVanishedErrorType` added to `System.IO.Error`
### ~~`base-4.15.0.0`~~
- [x] `hGetContents'`, `getContents'`, and `readFile'` added to `System.IO`
- [x] `singleton` added to `Data.List` and `Data.List.NonEmpty`
### `base-4.16.0.0`
- [x] `readBin` and `showBin` added to `Numeric`
- [x] [`oneBits` added to `Data.Bits`](https://gitlab.haskell.org/ghc/ghc/-/commit/8f610e52169eb63db7f8827d35553b84563d927c)
### ~~`base-4.17.0.0`~~
- [x] [`pattern TypeRep` added to `Type.Reflection`](https://gitlab.haskell.org/ghc/ghc/-/commit/d3ef2dc2bdfec457d5e0973f3e8f3e92767c16af)
- [x] [`(.^.)`, `(.>>.)`, `(.<<.)`, `(!>>.)`, and `(!<<.)` added to `Data.Bits`](https://gitlab.haskell.org/ghc/ghc/-/commit/baa969c39b511cad42ac4f806205fffffe201f5b)
### ~~`base-4.18.0.0`~~
- [x] [`liftA2` added to `Prelude`](https://gitlab.haskell.org/ghc/ghc/-/commit/442a94e8ef886b51c5622102546e34875a3fcc37)
- [x] [`traceWith`, `traceShowWith`, and `traceEventWith` added to `Debug.Trace`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7729)
- [x] [`inits1` and `tails1` added to `Data.List.NonEmpty`](https://gitlab.haskell.org/ghc/ghc/-/commit/8603c92113c49557f8632675a01f3b3874b819d1)
- [x] [`minusNaturalMaybe` added to `Numeric.Natural`](https://gitlab.haskell.org/ghc/ghc/-/commit/e6a69337ff54d0800ddf78f40f551559479502e8)
- [x] [`applyWhen` added to `Data.Function`](https://gitlab.haskell.org/ghc/ghc/-/commit/36fba0dfa2ecbd27b575dea09e4c3cdd6cb99b37)
- [x] [`mapAccumM` and `forAccumM` added to `Data.Traversable`](https://gitlab.haskell.org/ghc/ghc/-/commit/4b98c5ce971b4ea6a2ca9e44f2d068088546751a)
- [x] [`heqT` added to `Data.Type.Equality`](https://gitlab.haskell.org/ghc/ghc/-/commit/b3e98a926ac05b8e59e3b31b74b019d4ecb462f6)
### ~~`base-4.19.0.0`~~
- [x] [`unzip` added to `Data.Functor`](https://gitlab.haskell.org/ghc/ghc/-/commit/fa559c28d22888a4ba497daca2c1d5afdebb716c)
- [x] [`(!?)` added to `Data.List`](https://gitlab.haskell.org/ghc/ghc/-/commit/d53f6f4d98aabd6f5b28fb110db1da0f6db70a06)
- [x] [`unsnoc` added to `Data.List`](https://gitlab.haskell.org/ghc/ghc/-/commit/36d5944d13866e8c0d6634c38bb7a2f32fe98512)
- [x] [`getSolo` exported from `Data.Tuple`](https://gitlab.haskell.org/ghc/ghc/-/commit/45af8482e3f7d2d8234265982e14ff9b0d4dfa65)
- [x] [`decTypeRep`, `decT`, and `hdecT` added to `Data.Typeable`/`Type.Reflection`](https://gitlab.haskell.org/ghc/ghc/-/commit/858f34d5270936ff565880ed3ff244a0ab5f3987)
### ~~`base-4.20.0.0`~~
- [x] [`foldl'` added to `Prelude`](https://gitlab.haskell.org/ghc/ghc/-/commit/f1ec362817baa5d440a9f2b3a8b17e5513538119)
- [x] [`permutations` and `permutations1` added to `Data.List.NonEmpty`](https://gitlab.haskell.org/ghc/ghc/-/commit/9bc0dd1f36bf6eadcb35cfe0d278499ea3b25563)
- [x] [`sortOn` added to `Data.List.NonEmpty`](https://gitlab.haskell.org/ghc/ghc/-/commit/264a4fa91cc2f8f104f9c4af5ef4ed37cd615193)
- [x] [`List` added to `Data.List`](https://gitlab.haskell.org/ghc/ghc/-/commit/921fbf2fb601ff90cd9cbc0fb8fe3b1768a8f1d5)
### `base-4.21.0.0` (moved to #97)
* [ ] [`compareLength` added to `Data.List` and `Data.List.NonEmpty`](https://gitlab.haskell.org/ghc/ghc/-/commit/caf44a2ddfe007e840f6f212d3445d1cfe5c063e)
* [ ] [`inits1` and `tails1` added to `Data.List`](https://gitlab.haskell.org/ghc/ghc/-/commit/21fc180bec93d964a7f4ffdf2429ef6f74b49ab6)
* [ ] [`firstA` and `secondA` added to `Data.Bitraversable`](https://gitlab.haskell.org/ghc/ghc/-/commit/7c173310a82e796d0be262c629c9048becd50d50)

**Comment by bergmark** [comment]
What are your thoughts about the GHC modules? I'm missing for `GHC.Stack.prettySrcLoc` for example.

**Comment by RyanGlScott** [comment]
I would happily accept patches that added functionality from the `GHC.*` namespace. I haven't set out to do it myself since:

1. The `GHC.*` namespace is quite enormous.
2. The API tends to be quite volatile, so I imagine lots of CPP would be required to support it.
3. I personally don't have a need for it.

**Comment by sol** [comment]
@bergmark if you want to deal with call stack in a backward compatible way, you may want to look at https://github.com/sol/call-stack.

**Comment by RyanGlScott** [comment]
Now that `base-compat` has dropped support for pre-8.0 versions of GHC (see #96), the only unresolved items on this issue involve pre-8.0 GHCs and the as-of-yet-unreleased GHC 9.12. Going forward, I think it would be better to open individual issues for specific GHC versions. I'll opt to close this and track the GHC 9.12–related tasks separately in #97.
