### ISSUE TITLE
Remove GHC-6.12 support?

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/base-compat#25]
Currently, the `README` advertises that `base-compat` supports GHC-6.12. However, the current version currently fails to build with GHC-6.12.3 for various reasons. I could fix this, but I think it might be better to just drop GHC-6.12 support altogether, since:

* It's impractical to test GHC-6.12 on Travis CI, since the [Ubuntu GHC PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc) doesn't have a GHC-6.12.3 package for recent versions of Ubuntu.
* We use a pragma (`INLINEABLE`) that GHC-6.12 doesn't support.
* It's from a major version ago, and I'm aware of a number of major packages that won't build on GHC-6.12 anymore (`network` and `unordered-containers` come to mind).

These aren't insurmountable issues, but I'd be curious to know if people still require GHC-6.12 support. Otherwise, I'd be very tempted to remove it.

**Comment by sol** [comment]
I'm ok with dropping support for `6.12`.  I did the same thing for `hspec` (due to `async` being GHC `7.*` only).

**Comment by RyanGlScott** [comment]
In that case, should we remove `void` from `Control.Monad.Compat`? It was introduced in `base-4.3.0.0` (i.e., GHC 7.0), so it should be available on all supported versions of GHC.

**Comment by sol** [comment]
Yes, if we agree on dropping support for GHC `6.12` I think we should set an appropriate lower bound for `base` and remove unneeded `CPP`.

**Comment by RyanGlScott** [comment]
Alright, I've bumped up the lower `base` bound to 4.3 and "removed" `void` from `Control.Monad.Compat`. I'll proceed similarly with `base-orphans`.

**Comment by sol** [comment]
Ok, cool.  BTW, in general I think it makes sense to open and merge PRs most of the time, even if you just create the PR and merge it right away, for two reasons:

 * People who watch the repo (including me) will get an email for PRs, but not for direct pushes to master
 * Having a PR allows people to comment on it.  That is even true if it is merged right away and already closed

**Comment by sol** [comment]
Don't get me wrong, I think in this case it was ok to push it right to master as you mentioned it here anyway.  Just wanted to point out that PRs have advantages, even if you are not asking for a code review.

**Comment by RyanGlScott** [comment]
Yeah, I definitely should have been a little less bold :P. Sorry if it caused any difficulties.

**Comment by sol** [comment]
Nah, it's ok, don't worry ;)
