### ISSUE TITLE
Build fails in MinGHC 7.8.4 due to MIN_VERSION_base in System.Environment.Compat 

### ISSUE THREAD

**Issue by bkaes** [haskell-compat/base-compat#29]
Necessary steps to reproduce:

    cabal unpack base-compat
    cd base-compat-*
    cabal configure
    cabal build

`cabal build` fails with

    [ 2 of 19] Compiling System.Environment.Compat ( src\System\Environment\Compat.hs, dist\build\System\Environment\Compat.o )

    src\System\Environment\Compat.hs:41:20:
        Not in scope: type constructor or class `IO'

    src\System\Environment\Compat.hs:41:23:
        Not in scope: type constructor or class `DWORD'

    src\System\Environment\Compat.hs:43:27:
        Not in scope: type constructor or class `DWORD'

This seems linked to the `MIN_VERSION_base` macro in [`System.Environment.Compat`](https://github.com/haskell-compat/base-compat/blob/7c68acf02632f8a6f18600994d92797bd7a41548/src/System/Environment/Compat.hs#L18-L29):

    #if !(MIN_VERSION_base(4,7,0))
    import Prelude.Compat
    {- ... -}   
    #endif
The package build fine if one removes that macro or changes the minimum version to >4.7.0. Is this a quirk of MinGHC, or is the `MIN_VERSION` not correctly specified?

    $ cabal --version
    cabal-install version 1.22.2.0
    using version 1.22.2.0 of the Cabal library
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.4
    $ uname -a
    MINGW32_NT-6.2 xxxxx 1.0.18(0.48/3/2) 2012-11-21 22:34 i686 Msys

**Comment by RyanGlScott** [comment]
Hm, that's odd. I'll check it out sometime this weekend when I have access to a Windows machine.

**Comment by RyanGlScott** [comment]
The issue was due to me not surrounding the entirety of `System.Environment.Compat` with `#if !(MIN_VERSION_base(4,7,0))`, which caused some definitions to leak out on Windows that shouldn't have. I've released a new version ([`base-compat-0.8.1.1`](https://hackage.haskell.org/package/base-compat-0.8.1.1)) that fixes this.

**Comment by sol** [comment]
@RyanGlScott This may sound odd, but I tend to not push code changes in patch level releases at all.  The thing is that if you mess up something, your users can't work around it with `CPP`, as the `CPP` macros Cabal generates only take the first three digits of the version number into account.  For that reason I at least bump the minor version if I touched any code (in contrast to cabal file changes or documentation).

**Comment by RyanGlScott** [comment]
Whoops! Well, I'll try to atone by releasing a version with a minor version bump soon (I'll tackle at least part of issue #24).
