### ISSUE TITLE
Migrate run-check.sh to Haskell

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/base-compat#32]
The testing situation for `base-compat` is getting complicated enough to the point where conditionally running tests based on `MIN_VERSION_base` would be useful (here's a [possible example](https://github.com/haskell-compat/base-compat/pull/31)). To achieve this end, we need `run-check`'s tests to be defined in Haskell, not in Bash. Here are some possible approaches to achieve this:

1. Hardcode exceptions (e.g., `Data.Complex.Compat`, as proposed [here](https://github.com/haskell-compat/base-compat/pull/31)) directly into `typediff`
2. Make `typediff` a library and have `base-compat`'s test suite use its functionality directly from Haskell
3. Run a `typediff` process (using the `process` library)

Options 1 and 2 would require changes to `typediff`. Option 3 wouldn't require any `typediff` changes, but it feels a bit clunkier.

**Comment by sol** [comment]
I'm not exactly sure for what reason I went for binary releases, but I think it was because I didn't care to make it work with all versions on GHC.

**Comment by sol** [comment]
Hmm, I think it was because of `haskell-src-exts `, which takes for ever to build.

I'm fine with any approach, as long as it works on all supported versions of GHC.

Did you try whether `haskell-src-exts` builds on 7.0.*?

**Comment by RyanGlScott** [comment]
Oh, I forgot that it needs `haskell-src-exts`. In that case, option 2 isn't feasible, since `haskell-src-exts` requires `base` ≥ 4.5.

To avoid having to make a new release for `typediff` for each new exception to the the rule, I think I'll try option 3 for now.

**Comment by RyanGlScott** [comment]
Fixed in 75b0f31c6c1b819fe71c3e59395c70c6803554d8.
