### ISSUE TITLE
Missing 8.4 support

### ISSUE THREAD

**Issue by nomeata** [haskell-compat/base-compat#44]
It seems that `base-compat` does not yet support GHC 8.4. Presumably, you know about this, but I did not see an issue about this yet, so I created one to track the progress. (I am mostly interested in this because `wl-pprint-text` is blocked on this; see https://github.com/ivan-m/wl-pprint-text/issues/18).

**Comment by RyanGlScott** [comment]
Hi @nomeata.

#43 has an 8.4-ready implementation. I have not merged it yet since there are still lingering design questions to resolve being discussed in #36. (You may wish to chime in if you have an opinion on them.)

**Comment by RyanGlScott** [comment]
I've uploaded `base-compat-0.10.0` and `base-compat-batteries-0.10.0` to Hackage.
