### ISSUE TITLE
0.10.2: `$!` is parsed differently?

### ISSUE THREAD

**Issue by Mikolaj** [haskell-compat/base-compat#54]
My project builds fine with 0.10.1

https://ci.appveyor.com/project/Mikolaj/lambdahack/build/1.0.539

and breaks with 0.10.2

https://ci.appveyor.com/project/Mikolaj/lambdahack/build/1.0.540#L489

It looks as if `$!` is parsed differently. Who am I to blame?

BTW, thank you for your terrific work. Saves me a *lot* or time normally.

**Comment by Mikolaj** [comment]
Travis caught up, as well: https://travis-ci.org/LambdaHack/LambdaHack/jobs/399243677

**Comment by RyanGlScott** [comment]
Ack, I completely forgot to backport the proper fixity for `($!)`.

Thanks for the bug report—I'll work on getting a new release out ASAP.

**Comment by RyanGlScott** [comment]
I've uploaded [`base-compat-0.10.3`](http://hackage.haskell.org/package/base-compat-0.10.3) and [`base-compat-batteries-0.10.3`](http://hackage.haskell.org/package/base-compat-batteries-0.10.3) to Hackage.

**Comment by phadej** [comment]
I'd say we should add `base<0` to `base-compat-0.10.2`? It breaks `aeson`, which is nasty: https://github.com/bos/aeson/issues/650

**Comment by RyanGlScott** [comment]
Good thinking. I've done so in http://hackage.haskell.org/package/base-compat-0.10.2/revisions/ .
