### ISSUE TITLE
Prelude.Compat (as of base-compat-0.10.3) "isn't safe"

### ISSUE THREAD

**Issue by DanBurton** [haskell-compat/base-compat#56]
I'm seeing build failures on Stackage nightly for `step-function`, `lattices`, and `microformats2-parser`, which all have the same error message:

```
    Prelude.Compat: Can't be safely imported!
    The module itself isn't safe.
```

I'm assuming that either 
* it used to be explicitly marked as safe, or
* it was implicitly inferred to be safe

...but no longer is.

**Comment by RyanGlScott** [comment]
Indeed, I inadvertently made `Prelude.Compat` change from being inferred as safe to being inferred as unsafe by importing other unsafe things. I'll try to get a fix out soon.

**Comment by RyanGlScott** [comment]
I've uploaded [`base-compat-0.10.4`](http://hackage.haskell.org/package/base-compat-0.10.4) and [`base-compat-batteries-0.10.4`](http://hackage.haskell.org/package/base-compat-batteries-0.10.4) to Hackage, and deprecated `base-compat-0.10.3`.
