### ISSUE TITLE
Solo compatiblity

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-compat#76]
Tentative plan:

In OneTuple:
- Create a new module `Data.Tuple.Solo` which re-exports (GHC-9.0+) or defines (other GHC) `data Solo = Solo a`  and its selector (and instances).
  Older GHCs have `data Unit a = Unit a`, but I don't know how to make a good use of it. Clearer to define separate type IMO.

- Deprecate `Data.Tuple.OneTuple`, but re-export type alias `OneTuple = Solo` and pattern synonyms to make breakage smaller where possible

- Create `Data.Tuple.Solo.TH` with `tupleT` and `tupE` which use `Solo` on all supported GHCs (and other similar functions?)

In base-compat-batteries:
- Conditionally depend on `OneTuple` to get `Solo` for older GHCs.

(Future): instance compatibility:
- For GHC-9.0+ in base-orphan
- For older in `OneTuple`
- Reasoning: GHC-9.0+ users don't need to care about `OneTuple` package

OneTuple is missing Generic instances atm, which I will add. It may miss some other instances too, I have to grep GHC source code (or check haddocks from a branch where Solo is already re-exported).

**Comment by phadej** [comment]
https://hackage.haskell.org/package/OneTuple-0.3 is on hackage

**Comment by RyanGlScott** [comment]
See #79.

**Comment by RyanGlScott** [comment]
I've uploaded [`base-compat-0.12.1`](https://hackage.haskell.org/package/base-compat-0.12.1) and [`base-compat-batteries-0.12.1`](https://hackage.haskell.org/package/base-compat-batteries-0.12.1) to Hackage with these changes.
