### ISSUE TITLE
Add policy that `Prelude.Compat` imports change only in major versions of base-compat

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-compat#82]
This is because `Prelude.Compat` is designed to be imported unqualified instead of `Prelude`. Therefore any addition to the imports may cause breakage in downstream.

I think this policy will make things more robust at almost no cost as new  `Prelude.Compat` imports are added rarely.

**Comment by sol** [comment]
Would it make sense to extend this policy to all the modules.  As I understand it, from a user's perspective there is no benefit from getting new exports from a minor release.

**Comment by phadej** [comment]
> Would it make sense to extend this policy to all the modules. As I understand it, from a user's perspective there is no benefit in getting new exports from a minor release.

No. PVP explicitly allows adding new exports in minor versions, as in well-written code imports are either qualifier or use explicit import lists. `Prelude.Compat` module is special.

**Comment by RyanGlScott** [comment]
I'm fine with having changes to `Prelude.Compat` be accompanied by a major version bump as a general rule, given how many things import `Prelude.Compat` unqualified. Like all general rules, I can imagine there could be rare exceptions. For instance, I looked through the changelog to see on what occasions `Prelude.Compat` has changed in minor releases, and I only found one such occasion: `Prelude.Compat` [enabled `BangPatterns` in 0.10.5](https://github.com/haskell-compat/base-compat/blob/bc742ba14b316759a7f5606e9fd737e91d6d9c37/base-compat/CHANGES.markdown#changes-in-0105-20181018), which makes sense, given that it doesn't impact the API. For changes that do impact the API (even if they're just API additions), I'd favor being more cautious.

**Comment by RyanGlScott** [comment]
This will be relevant for the next `base-compat` release supporting GHC 9.6, as `base-4.18.0.0` (bundled with GHC 9.6) re-exports `liftA2` from the `Prelude`. (See #24.) We will need to change `Prelude.Compat` to mirror this change, so now would be a good time to enshrine the policy that changes to `Prelude.Compat` imply a major version bump in `base-compat`.
