### ISSUE TITLE
Generically/1

### ISSUE THREAD

**Issue by phadej** [haskell-compat/base-compat#84]
base-4.17 will include these new newtypes. It would be great to have them somewhere in a compat package. 

- [`generic-deriving`](https://hackage.haskell.org/package/generic-deriving) could be one place, but it feels "heavy".
- create a new package, e.g. `generically`.

If latter option is chosen, the `base-compat-batteries` may or may not re-export it, but `generic-deriving` could.

Does @RyanGlScott have an opinion on this? I prefer latter, but I'll be happy to sketch either option.

**Comment by RyanGlScott** [comment]
`base-compat` has a policy of not backporting data type definitions (see [here](https://github.com/haskell-compat/base-compat/tree/a46f5237d840280391e0f5ae4845d138fe1db78d/base-compat#data-types-and-type-classes)), so I would prefer having a dedicated package for this purpose. As you've noted, `generic-deriving` might be a somewhat awkward fit for this purpose, so a separate `generically` package might be best. Would you want to put `generically` under the `haskell-compat` organization?

**Comment by phadej** [comment]
> Would you want to put generically under the haskell-compat organization?

That would make a lot of sense.

I created a stub package at https://github.com/phadej/generically, but I'll be happy to transfer it under this org.

**Comment by RyanGlScott** [comment]
> I created a stub package at https://github.com/phadej/generically, but I'll be happy to transfer it under this org.

Cool. Do I need to do anything before it can be transferred over to `haskell-compat`?

**Comment by phadej** [comment]
If I try to transfer it I get *You don’t have the permission to create public repositories on haskell-compat* error from GitHub. So either I'd need rights to do that, or you could just create a new repo and push the contents there.

**Comment by RyanGlScott** [comment]
Alright. In that case, I've created https://github.com/haskell-compat/generically and given you the appropriate permissions.

**Comment by phadej** [comment]
Thanks. I'd appreciate a review of it.

I put the lowest supported GHC version at GHC-8.0, as it was easy (e.g. no need to think about Eq1 stuff pre base-4.9), and it's still low enough that in most libraries nowadays one won't need to worry about CPP when defining instances for `Generically`.

I already uploaded a candidate, I'll add you as a maintainer on Hackage too.

**Comment by phadej** [comment]
> although I'll need to think about what this means for base-compat-batteries, 

E.g. https://hackage.haskell.org/package/base-compat-batteries-0.12.1/docs/src/Data.Type.Equality.Compat.html isn't uniform API either. It's probably possible to push `generically` support all the way down to GHC-7.0, but I don't know if it's worth the trouble.

**Comment by RyanGlScott** [comment]
True, I forgot about `type-equality`. In that case, if we decide to re-export `generically` from `base-compat-batteries`, we can simply do so only on GHC 8.0 or later.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/generically-0.1 published
